routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
Route::get('/privacy', function () {
    return view('legals');
});

Route::get('/terms', function () {
    return view('tsandcs');
});
*/

Auth::routes();
Route::get('/admin', 'Admin\\DashboardController@index')->name('admin.dashboard');
Route::get('/admin/login', 'Admin\\Auth\\LoginController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Admin\\Auth\\LoginController@login')->name('admin.login');
Route::post('/admin/logout', 'Admin\\Auth\\LoginController@logout')->name('admin.logout');
Route::get('/pages/{slug}', 'PageController@show')->name('pages.show');

// Client routes
Route::group(['middleware' => ['auth','active','client']], function()
{
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/questions/basic', 'QuestionController@basic')->name('questions.basic');
	Route::get('/questions/faq', 'QuestionController@faq')->name('questions.faq');
	Route::resource('company', 'CompanyController');
	Route::resource('questions', 'QuestionController');
	Route::resource('services', 'CompanyServicesController');
});

// Admin routes
Route::group(['middleware' => ['auth','active','admin'], 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function()
{
	Route::get('users/create', 'UserController@create')->name('users.create');
	Route::post('users', 'UserController@store')->name('users.store');
	Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
	Route::put('users/{user}', 'UserController@update')->name('users.update');

	Route::get('companies/create', 'CompanyController@create')->name('companies.create');
	Route::post('companies', 'CompanyController@store')->name('companies.store');
	Route::get('companies/{user}/edit', 'CompanyController@edit')->name('companies.edit');
	Route::put('companies/{user}', 'CompanyController@update')->name('companies.update');

	Route::get('alerts', 'AlertController@index')->name('alerts.index');
	Route::get('alerts/create', 'AlertController@create')->name('alerts.create');
	Route::get('alerts/{id}', 'AlertController@show')->name('alerts.show');
	Route::post('alerts', 'AlertController@store')->name('alerts.store');
	Route::get('alerts/{id}/edit', 'AlertController@edit')->name('alerts.edit');
	Route::put('alerts/{id}', 'AlertController@update')->name('alerts.update');
	
	
	
	
//	Route::resource('users', 'UserController');
//	Route::resource('companies', 'CompanyController');
	Route::resource('servicecategories', 'ServicecategoryController');
	Route::resource('services', 'ServiceController');
//	Route::resource('companyservices', 'CompanyServicesController');
	Route::post('bills/getservices', 'BillController@getServices')->name('bills.getservices');
	Route::post('bills/filter', 'BillController@filter')->name('bills.filter');
	Route::get('bills/createallbills', 'BillController@createAllBills')->name('bills.createallbills');
	Route::get('bills/saveallbills/{year}/{month}', 'BillController@saveAllBills')->name('bills.saveallbills');
	Route::get('bills/exportbills/{year}/{month}', 'BillController@export')->name('bills.export');
	Route::resource('bills', 'BillController');

	Route::resource('queues', 'QueueController');
	Route::get('queues/company/{company_id}', 'QueueController@company')->name('queues.company');

	Route::post('company/filter', 'CompanyController@filter')->name('companies.filter');
	Route::post('companyservices/filter', 'CompanyServicesController@filter')->name('companyservices.filter');
	Route::resource('webchats', 'WebchatController');
	Route::resource('basicquestionmasters', 'BasicquestionmasterController');

	Route::resource('pages', 'PageController');
	Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

	

});



/* Staff  */
Route::group(['middleware' => ['auth','active','staff'], 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function()
{
	Route::get('users', 'UserController@index')->name('users.index');
	Route::get('users/{user}', 'UserController@show')->name('users.show');

	Route::get('companies', 'CompanyController@index')->name('companies.index');
	Route::get('companies/{company}', 'CompanyController@show')->name('companies.show');

	Route::get('companyservices/create', 'CompanyServicesController@create')->name('companyservices.create');
	Route::get('companyservices', 'CompanyServicesController@index')->name('companyservices.index');
	Route::get('companyservices/{company}', 'CompanyServicesController@show')->name('companyservices.show');
	Route::post('companyservices', 'CompanyServicesController@store')->name('companyservices.store');
	Route::get('companyservices/{user}/edit', 'CompanyServicesController@edit')->name('companyservices.edit');
	Route::put('companyservices/{user}', 'CompanyServicesController@update')->name('companyservices.update');

	Route::get('questions/filter', 'QuestionController@filter')->name('questions.filter');
	Route::get('questions/basic', 'QuestionController@basic')->name('questions.basic');
	Route::resource('questions', 'QuestionController');

	Route::get('calls','CallController@index')->name('calls.index');
	Route::get('phonecontacts','PhonecontactController@index')->name('phonecontacts.index');

	Route::get('notes/filter', 'NoteController@filter')->name('notes.filter');
	Route::get('notes/create', 'NoteController@create')->name('notes.create');
	Route::get('notes', 'NoteController@index')->name('notes.index');
	Route::get('notes/{company}', 'NoteController@show')->name('notes.show');
	Route::post('notes', 'NoteController@store')->name('notes.store');
//	Route::get('notes/{user}/edit', 'NoteController@edit')->name('notes.edit');
//	Route::put('notes/{user}', 'NoteController@update')->name('notes.update');
	
});

Route::get('/{slug}', 'PageController@show')->name('pages.show');
	

app/Bill.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bill extends Model
{
    use \App\Traits\Userstamps;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'start_date','end_date','status', 'total', 'company_id','notes'
    ];
    

    /**
     * Get the company for this bill.
     */
    public function company()
    {
        return $this->belongsTo('App\Company');
    }

    /**
     * Get the line items for this Bill.
     */
    public function lineitems()
    {
        return $this->hasMany('App\Lineitem');
    }


    /**
     * Get the line items for this Bill.
     */
    public function xerolineitems()
    {
        return $this->hasMany('App\Xerolineitem');
    }
    
    
    public function createdby() 
    {
        return $this->belongsTo('App\User', 'created_by');
    }

    public function updatedby() 
    {
        return $this->belongsTo('App\User', 'updated_by');
    }
    
    public function getRules() 
    {
        return $this->rules;
    }

    public function getMessages() 
    {
        return $this->messages;
    }

	public function getInvoiceNumber()
	{
		return "HP" . str_pad($this->id,6,"0",STR_PAD_LEFT);
	}
    
    
}

app/Http/Controllers/Admin/BillController.php
<?php

namespace App\Http\Controllers\Admin;

use League\Csv\Writer;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Pagination\LengthAwarePaginator;
use App\Http\Controllers\Controller;
use App\Company;
use App\CompanyServices;
use App\Bill;
//use App\Lineitem;
use App\Xerolineitem;
use App\Exportlineitem;
use Validator;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;
use Illuminate\Support\Facades\Log;


class BillController extends Controller
{
	
	private $start_date;
	private $end_date;
	private $month;
	private $year;
	
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $allCompanies = Company::All();
        $filter = ['fcompany'=>0];
        $bills = Bill::with(['xerolineitems','company'])->paginate(10);
        return view('admin.bills.list', ['bills' => $bills, 'filter'=>$filter,'allCompanies' => $allCompanies]);
        
    }

    public function filter(Request $request)
    {
        $whereArray = [];
        if($request->fcompany > 0) {
               $whereArray[] = ['company_id','=',$request->fcompany];
        } 
        $bills = Bill::with(['xerolineitems','company'])->where($whereArray)->paginate(10);
                
        $allCompanies = Company::All();
        $filter = ['fcompany'=>$request->fcompany];
        return view('admin.bills.list', ['bills' => $bills, 'filter'=>$filter,'allCompanies' => $allCompanies]);
    }
    
    /**
     * Get a list of valid CompanyServices for this bill
     *
     * Request will include the company and start and end dates.
     * Search for CompanyServices where the start date is after bill start and end date is blank or after bill end date.
     * The "prorata" value is calculated just in case a service started or ended part way through the bill period.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $company_id Key to company for this bill
     * @param  date                     $start_date Start date for this bill period
     * @param  date                     $end_date   end Date for this bill period
     * @return \Illuminate\Http\Response
     */
    public function getServices(Request $request)
    {
        
        $company_id = $request->company_id;
        $first_bill_date = new Carbon($request->start_date);
        //		$first_bill_date = new Carbon('first day of last month');
        $first_bill_date->setTime(0, 0, 0);
        $last_bill_date = new Carbon($request->end_date);
        //		$last_bill_date = new Carbon('last day of last month');
        $last_bill_date->setTime(23, 59, 59);

        $where = [
        ['company_id','=',$company_id],
        //['status','=','Approved'],
        ['start_date', '<=', $last_bill_date],
        ];

        $company = Company::find($company_id);
        $companyservices = CompanyServices::where($where)->where(
            function ($query) use ($first_bill_date) {
                $first_bill_date = new Carbon('first day of last month');
                $query->whereNull('end_date')->orWhere('end_date', '>=', $first_bill_date);
            }
        )
		->with(['phonelogs'=> function ($query) use ($first_bill_date,$last_bill_date) {
				$query->whereBetween('datetime',[$first_bill_date,$last_bill_date]);
		}])
		->withCount(['webchats AS onlinechats' => function ($query) use ($first_bill_date,$last_bill_date) {
				$query->where('type', 'chat')->whereBetween('created_at_date',[$first_bill_date,$last_bill_date]);
		}])->get();
		
        
        $xerolineitems = [];
        foreach($companyservices as $companyservice) {
			// check if the company service started or ended this month and pro rata the costs accordingly
            if ($companyservice->end_date == null || $companyservice->end_date >= $last_bill_date) {
                $prorata = 1;
            } else {
                $enddate = new Carbon($companyservice->end_date);
                $days = $first_bill_date->diffInDays($enddate);
                $prorata = round(($days /  $first_bill_date->daysInMonth), 2);
            }
			
			// create base costs for services that have a fixed charge element
			if($companyservice->service->basecost != null) {
               $xerolineitems[] = [
                'id' => $companyservice->id,
                'description' => $companyservice->service->name . " BASE",
                'unitamount' => $companyservice->service->basecost,
                'maxusage' => null,
                'accountcode' => $companyservice->service->accountcode,
                'discount' => 0,
                'quantity' => $prorata,
                'total' => round(($prorata * floatval($companyservice->service->basecost)), 2)
				];
			}

			// create variable cost for services that have a unit cost element
			if($companyservice->service->extracost > 0) {
				$quantity = 0;
				// check the service has a webchat id
				if ($companyservice->widget_id) {
					// now get the count of webchats
					$quantity = $companyservice->onlinechats_count;
				}

				// check if the service has a dataset (linked to phone charges)
				if ($companyservice->datasetid) {
					// now get the count of webchats
						$quantity = $companyservice->phonelogs->sum('duration');
						if ($quantity > 0) {
							$quantity = round(($quantity / 60),2);
						}
				}

				
				$total = ($quantity - $companyservice->service->maxusage) * $companyservice->service->extracost;
				if ($total < 0) {
					$total = 0;
				}
				
               $xerolineitems[] = [
                'id' => $companyservice->id,
                'description' => $companyservice->service->name . " USAGE",
                'unitamount' => $companyservice->service->extracost,
                'maxusage' => $companyservice->service->maxusage,
                'accountcode' => $companyservice->service->accountcode,
                'discount' => 0,
                'quantity' => $quantity,
                'total' => $total
               ];
			}
        }

        
        return json_encode(['xerolineitems' => $xerolineitems,'billdetails'=>['company_id'=>$company->id,'company'=>$company,'start_date'=>$first_bill_date->toDateString(),'end_date'=>$last_bill_date->toDateString()]]);
    }

    /**
     * Create a new bill
     *
     * Show the "add" bill view where the user can choose a company and set the start and end date for this bill
     *
     * @return \Illuminate\Http\Response
     */
    function create()
    {
        $companies = Company::select(['id','companyname'])->get()->toJSON();
        return view('admin.bills.add', ['companies'=>$companies]);
        
    }
    /**
     * Store a newly created bill and associated lineitems.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //		return json_encode([$request->lineitems,$request->billdetails,$request->total]);

        $rules = [
        'billdetails.company_id' => 'required',
        'billdetails.start_date' => 'required|date',
        'billdetails.end_date' => 'required|date',
        'xerolineitems' => 'required',
        ];
                    
        $messages = [
        'billdetails.start_date.required' => 'You must provide a start date for this bill',
        'billdetails.end_date.required' => 'You must provide an end date for this bill',
        ];

        $this->validate($request, $rules, $messages);

        $newBill = new Bill();
        
        $newBill->company_id = $request->billdetails['company_id'];
        $newBill->start_date = $request->billdetails['start_date'];
        $newBill->end_date = $request->billdetails['end_date'];
        $newBill->status = "draft";
        $newBill->total = $request->total;
        
        if ($newBill->save()) {
               $linetotal = 0;
            foreach($request->xerolineitems as $xerolineitem) {
                $newXerolineitem = new Xerolineitem();
                $newXerolineitem->bill_id = $newBill->id;
                $newXerolineitem->company_services_id = $xerolineitem['id'];
                $newXerolineitem->description = $xerolineitem['description'];
                $newXerolineitem->accountcode = $xerolineitem['accountcode'];
                $newXerolineitem->discount = $xerolineitem['discount'];
                $newXerolineitem->unitamount = $xerolineitem['unitamount'];
				if ($xerolineitem['quantity'] > $xerolineitem['maxusage']) {
					$newXerolineitem->quantity = $xerolineitem['quantity'] - $xerolineitem['maxusage'];
				} else {
					$newXerolineitem->quantity = 0;
				}
                $newXerolineitem->total = round((($newXerolineitem['quantity'] * $newXerolineitem['unitamount']) * ((100 - $newXerolineitem['discount'])/100)),2);
                $linetotal += $newXerolineitem->total;
                
                $newXerolineitem->save();
            }
            if (round($linetotal,2) == round($request->total,2)) {
                // something does not add up
                return json_encode(true);
            } else {
                return json_encode([false,'errors'=>[['invalid total'=>'total bill does not match input'],['total'=>$request->total,'line'=>$linetotal]]]);
            }
            
        }
        return json_encode([false,'errors'=>[['invalid new bill'=>'new bill not saved']]]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $bill = Bill::with('xerolineitems', 'company')->find($id);
		$bill->invoicenumber = $bill->getInvoiceNumber();
        return view('admin.bills.show', ['bill' => $bill]);
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    /**

resources/views/admin/bills/add.blade.php
@extends('admin.layouts.app')

@section('title','Bills - create new bill')

@section('content')
<div id="lineitems" class="container">

@if(count($errors)>0)
	<div class="alert alert-warning">Sorry but there are errors with this bill; please correct them and ty to save again</div>
@endif

	<div>
		<form class="form form-inline" @submit.prevent="getServices()">
			<label for="company">Company:</label>
			<select name="company" v-model="billdetails.company_id">
				<template v-for="company in companies">
					<option v-bind:value="company.id">@{{ company.companyname}}</option>
				</template>	
			</select>
			<label for="start_date">Start:</label>
			<datepicker v-model="billdetails.start_date" ></datepicker>
			<label for="end_date">End:</label>
			<datepicker v-model="billdetails.end_date" ></datepicker>
			<button type="submit" class="btn btn-sm  btn-primary" ><span class="icon icon-funnel"></span> Find Services</button>
		</form>
	</div>

	<div v-cloak v-if="billdetails.company != null">	
		<div  v-cloak>@{{ billdetails.company.companyname}}</div>
		<div  v-cloak>@{{ billdetails.start_date}}</div>
		<div  v-cloak>@{{ billdetails.end_date}}</div>
	</div>

	<div c-cloak v-if="lineitems">
	<form class="form" @submit.prevent="saveBill()">
			<table class="table">
				<thead>
					<th>Service Description</th>
					<th>Account Code</th>
					<th>Unit Amount</th>
					<th>Inclusive Qty</th>
					<th>Quantity</th>
					<th>Discount</th>
					<th>Total</th>
				</thead>
				<tbody>
		<template v-for="lineitem in lineitems">
				<tr>
					<td><p class="form-control-static">@{{lineitem.description}}</p></td>
					<td><p class="form-control-static">@{{lineitem.accountcode}}</p></td>
					<td><p class="form-control-static">@{{lineitem.unitamount}}</p></td>
					<td><p class="form-control-static">@{{lineitem.maxusage}}</p></td>
					<td><input class="form-control" type="number" 
							v-model.number="lineitem.quantity" 
							v-on:blur="updateQuantity(lineitem)"
							v-bind:readonly="lineitem.maxusage == null" 
							>
					</td>
					<td><input class="form-control" type="number" min="0" max="100"
							v-model.number="lineitem.discount"
 							v-on:blur="updateDiscount(lineitem)"
							>
					</td>
					<td><input type="text" class="form-control" v-model.number="lineitem.total" type="number" readonly></td>
				</tr>
		</template>
				<tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>Bill Total</td>
					<td v-cloak>@{{totalBill}}</td>
				</tr>
				</tbody>
			</table>  
		<div class="row">	
			<div class="col-sm-3 offset-sm-6">
				<button type="submit" class="btn btn-sm  btn-primary" ><span class="glyphicon glyphicon-save"></span> Save</button>
			</div>
		</div>
	</form>
	</div>
	
</div>
@endsection
@section('addscripts')
<script src="{{ asset('js/vue.js') }}"></script>
<script>
toastr.options = {
  "positionClass": "toast-bottom-right",
}


    var vm = new Vue({
          el: '#lineitems',
          data: {
			companies: {!! $companies !!},
			billdetails: {
				company_id: 0,
				start_date: Moment().subtract(1,'months').startOf('month').format('YYYY-MM-DD'),
				end_date: Moment().subtract(1,'months').endOf('month').format('YYYY-MM-DD'),
				company: null
			},
			lineitems: null,
			formerrors: null,
          },
			computed: {
			  totalBill: function(){
				let sumLines = 0;
					for(let i = 0; i < this.lineitems.length; i++){
					  sumLines += parseFloat(this.lineitems[i].total);
					}
					return sumLines.toFixed(2);
				}
			},
		  methods: {
			getServices: function() {
				var _this = this;
				this.billdetails.start_date = Moment(this.billdetails.start_date).format('YYYY-MM-DD');
				this.billdetails.end_date = Moment(this.billdetails.end_date).format('YYYY-MM-DD');
				axios.post('{{ route("admin.bills.getservices") }}',this.billdetails)
					.then(function (response) {
						_this.lineitems = response.data.xerolineitems;
						_this.billdetails = response.data.billdetails;
					})
					.catch(function (error)	{
					});
			},
			updateQuantity: function(li) {
				if(li.quantity > li.maxusage) {
					total = ((li.quantity - li.maxusage) * li.unitamount);
				} else {
					total = 0;
				}
				li.total = total.toFixed(2);
			},
			updateDiscount: function(li) {
				if (li.quantity > li.maxusage) {
					qtyCharged = li.quantity - li.maxusage;
				} else {
					qtyCharged = 0;
				}
				total = ((qtyCharged * li.unitamount) * (100 - li.discount)/100);
				li.total = total.toFixed(2);
			},
			saveBill: function() {
				this.billdetails.start_date = Moment(this.billdetails.start_date).format('YYYY-MM-DD');
				this.billdetails.end_date = Moment(this.billdetails.end_date).format('YYYY-MM-DD');
				axios.post('{{ route("admin.bills.store") }}',{'xerolineitems': this.lineitems,'billdetails': this.billdetails,'total':this.totalBill})
					.then(function (response) {
						toastr.success('Bill saved','Success!');
					})
					.catch(function (error)	{
						toastr.error('Bill not saved','Oops!');
						console.log(error);
					});
			  }		  
		},
		components: {
				'datepicker': Datepicker
		},
    });

 
</script>
@endsection

resources/views/admin/bills/allbills.blade.php
@extends('admin.layouts.app')

@section('title','Bills - create new bills')

@section('content')
<div id="bills" class="container">

@if(count($errors)>0)
	<div class="alert alert-warning">Sorry but there are errors with these bill; please correct them and ty to save again</div>
@endif

	<div>
		<form class="form form-inline" @submit.prevent="createBills()">
			<label for="selected_year">Year:</label>
			<select v-model="selected_year">
				<option v-for="year in years" v-bind:value="year"  :selected="year == selected_year">@{{year}}</option>
			</select>
			<label for="selected_month">Month:</label>
			<select v-model="selected_month">
				<option v-for="(month, index) in months" v-bind:value="index + 1"   :selected="index + 1 == selected_month">@{{month}}</option>
			</select>
			
			<button type="submit" class="btn btn-sm  btn-primary" ><span class="icon icon-save"></span> Create Bills</button>
		</form>
	</div>

	<div v-show="loading">
		<span class="glyphicon glyphicon-repeat fast-right-spinner"></span> Creating Bill, please wait......
	</div>
	
	<div id="download" v-show="download">
		<a v-bind:href="downloadUrl" class="btn btn-primary">Download CSV<a>
	</div>
	
</div>
@endsection
@section('addscripts')
<script src="{{ asset('js/vue.js') }}"></script>
<script>
toastr.options = {
  "positionClass": "toast-bottom-right",
}


    var vm = new Vue({
		el: '#bills',
		data: {
			years: [2017,2018,2019,2020],
			months: ["January","February","March","April","May","June","July","August","September","October","November","December"],
			selected_year: parseInt(Moment().subtract(1,'months').startOf('month').format('YYYY')),
			selected_month: parseInt(Moment().subtract(1,'months').startOf('month').format('M')),
			formerrors: null,
			download: false,
			loading: false
		},
		computed: {
			downloadUrl: function() {
				return "{{url('/admin/bills/exportbills')}}/" + this.selected_year + "/" + this.selected_month
			}
		},
		methods: {
			createBills: function() {
				var _this = this;
				this.download = false;
				this.loading = true;
				axios.get("{{url('/admin/bills/saveallbills')}}/" + this.selected_year + "/" + this.selected_month)
					.then(function (response) {
						_this.download = true;
						_this.loading = false;
						if (response.data == 1) {
							toastr.success('Bills already exist','Success!');
						}
						if (response.data == 2) {
							toastr.success('Bills created','Success!');
						}
					})
					.catch(function (error)	{
						toastr.error('Bills not saved','Oops!');
						console.log(error);
						_this.loading = false;
						_this.download = false;
					});
			  }		  
		},
	});

 
</script>
@endsection

resources/views/admin/bills/list.blade.php
@extends('admin.layouts.app')

@section('title','Bills')

@section('content')
<div class="container">
		<div class="toolbar">
			<div class="btn-group dashhead-toolbar-item">
				  <a title="Create Bills" type="button" class="btn btn-outline-primary" href="{{route('admin.bills.createallbills')}}">
					<span class="icon icon-add-to-list"></span> Create Bills
				  </a>
			</div>
			<form id="company_filter" class="form form-navbar" action="{{ route('admin.bills.filter') }}" method="post" role="form" style="display: block;">
					{{ csrf_field() }}
			<div class="dashhead-toolbar-item form-group">		
				<select name="fcompany" id="fcompany" class="form-control">
					<option value="0">Any Company</option>
					@foreach($allCompanies as $company)
					<option value="{{$company->id}}"  
						@if($filter['fcompany'] == $company->id) 
							selected
						@endif 
					>{{$company->getRef()}} - {{$company->companyname}}</option>
					@endforeach
				</select>
			</div>
			<div class="dashhead-toolbar-item form-group">		
			</div>
			<div class="btn-group dashhead-toolbar-item">
					<button type="submit" name="filtercompany-submit" id="filtercompany-submit" tabindex="4" class="btn btn-outline-primary"> 
					<span class="icon icon-funnel"></span> Filter</button>
			</div>
			</form>		
		</div>
</div>



<div class="col-md-12">
<div class="row">
	<div class="col-sm-8">
	 {{ $bills->links() }}
	</div>
</div>
<div class="row">
	<div>
	<table id="billTable" class="table table-responsive" data-sort="table">
		<thead>
			<tr>
				<th class="header">View Bill</th>
				<th class="header">Company Name</th>
				<th class="header">Start Date</th>
				<th class="header">End Date</th>
				<th class="header">Status</th>
				<th class="header">Total</th>
				<th class="header">Line Items</th>
			</tr>
		</thead>
	<tbody>
	@foreach($bills as $bill)
	<tr>
		<td><a href="{{route('admin.bills.show',['id'=>$bill['id']])}}">{{$bill['id']}}</a></td>
		<td>{{$bill->company->companyname}}</td>
		<td>{{$bill->start_date}}</td>
		<td>{{$bill->end_date}}</td>
		<td>{{$bill->status}}</td>
		<td>{{$bill->total}}</td>
		<td>{{$bill->xerolineitems->count()}}</td>
	</tr>
	@endforeach
	</tbody>
	</table>
	</div>
</div>
<div class="row">
	<div class="offset-col-8 col-sm-4">
	{{ $bills->links() }}
	</div>
</div>
</div>




@endsection
@section('addscripts')
@endsection

resources/views/admin/bills/show.blade.php
@extends('admin.layouts.app')

@section('title','Bills - view bill')

@section('content')
<div id="bill" class="container">

	<div v-cloak v-if="bill.company != null">	
		<div  v-cloak>Company:  @{{ bill.company.companyname}}</div>
		<div  v-cloak>Invoice:  @{{ bill.invoicenumber}}</div>
		<div  v-cloak>Billing peroid: from @{{ bill.start_date}} to @{{ bill.end_date}}</div>
	</div>

	<table class="table">
		<thead>
			<th>Service Description</th>
			<th class="text-right">Unit Cost</th>
			<th class="text-right">Quantity</th>
			<th class="text-right">Line Total</th>
		</thead>
		<tbody>
			<tr v-cloak v-for="lineitem in bill.xerolineitems">
				<td><p class="form-control-static">@{{lineitem.description}}</p></td>
				<td class="text-right"><p class="form-control-static">@{{lineitem.unitamount}}</p></td>
				<td class="text-right"><p class="form-control-static">@{{lineitem.quantity}}</p></td>
				<td class="text-right"><p class="form-control-static">@{{lineitem.total}}</p></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td  class="text-right">Bill Total</td>
				<td  class="text-right" v-cloak>@{{bill.total}}</td>
			</tr>
		</tbody>
	</table>  
	
</div>
@endsection
@section('addscripts')
<script src="{{ asset('js/vue.js') }}"></script>
<script>


    var vm = new Vue({
          el: '#bill',
          data: {
			bill: {!! $bill !!}
          }
    });

 
</script>
@endsection