routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
Route::get('/privacy', function () {
    return view('legals');
});

Route::get('/terms', function () {
    return view('tsandcs');
});
*/

Auth::routes();
Route::get('/admin', 'Admin\\DashboardController@index')->name('admin.dashboard');
Route::get('/admin/login', 'Admin\\Auth\\LoginController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Admin\\Auth\\LoginController@login')->name('admin.login');
Route::post('/admin/logout', 'Admin\\Auth\\LoginController@logout')->name('admin.logout');
Route::get('/pages/{slug}', 'PageController@show')->name('pages.show');

// Client routes
Route::group(['middleware' => ['auth','active','client']], function()
{
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/questions/basic', 'QuestionController@basic')->name('questions.basic');
	Route::get('/questions/faq', 'QuestionController@faq')->name('questions.faq');
	Route::resource('company', 'CompanyController');
	Route::resource('questions', 'QuestionController');
	Route::resource('services', 'CompanyServicesController');
});

// Admin routes
Route::group(['middleware' => ['auth','active','admin'], 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function()
{
	Route::get('users/create', 'UserController@create')->name('users.create');
	Route::post('users', 'UserController@store')->name('users.store');
	Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
	Route::put('users/{user}', 'UserController@update')->name('users.update');

	Route::get('companies/create', 'CompanyController@create')->name('companies.create');
	Route::post('companies', 'CompanyController@store')->name('companies.store');
	Route::get('companies/{user}/edit', 'CompanyController@edit')->name('companies.edit');
	Route::put('companies/{user}', 'CompanyController@update')->name('companies.update');

	Route::get('alerts', 'AlertController@index')->name('alerts.index');
	Route::get('alerts/create', 'AlertController@create')->name('alerts.create');
	Route::get('alerts/{id}', 'AlertController@show')->name('alerts.show');
	Route::post('alerts', 'AlertController@store')->name('alerts.store');
	Route::get('alerts/{id}/edit', 'AlertController@edit')->name('alerts.edit');
	Route::put('alerts/{id}', 'AlertController@update')->name('alerts.update');
	
	
	
	
//	Route::resource('users', 'UserController');
//	Route::resource('companies', 'CompanyController');
	Route::resource('servicecategories', 'ServicecategoryController');
	Route::resource('services', 'ServiceController');
//	Route::resource('companyservices', 'CompanyServicesController');
	Route::post('bills/getservices', 'BillController@getServices')->name('bills.getservices');
	Route::post('bills/filter', 'BillController@filter')->name('bills.filter');
	Route::get('bills/createallbills', 'BillController@createAllBills')->name('bills.createallbills');
	Route::get('bills/saveallbills/{year}/{month}', 'BillController@saveAllBills')->name('bills.saveallbills');
	Route::get('bills/exportbills/{year}/{month}', 'BillController@export')->name('bills.export');
	Route::resource('bills', 'BillController');

	Route::resource('queues', 'QueueController');
	Route::get('queues/company/{company_id}', 'QueueController@company')->name('queues.company');

	Route::post('company/filter', 'CompanyController@filter')->name('companies.filter');
	Route::post('companyservices/filter', 'CompanyServicesController@filter')->name('companyservices.filter');
	Route::resource('webchats', 'WebchatController');
	Route::resource('basicquestionmasters', 'BasicquestionmasterController');

	Route::resource('pages', 'PageController');
	Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

	

});



/* Staff  */
Route::group(['middleware' => ['auth','active','staff'], 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function()
{
	Route::get('users', 'UserController@index')->name('users.index');
	Route::get('users/{user}', 'UserController@show')->name('users.show');

	Route::get('companies', 'CompanyController@index')->name('companies.index');
	Route::get('companies/{company}', 'CompanyController@show')->name('companies.show');

	Route::get('companyservices/create', 'CompanyServicesController@create')->name('companyservices.create');
	Route::get('companyservices', 'CompanyServicesController@index')->name('companyservices.index');
	Route::get('companyservices/{company}', 'CompanyServicesController@show')->name('companyservices.show');
	Route::post('companyservices', 'CompanyServicesController@store')->name('companyservices.store');
	Route::get('companyservices/{user}/edit', 'CompanyServicesController@edit')->name('companyservices.edit');
	Route::put('companyservices/{user}', 'CompanyServicesController@update')->name('companyservices.update');

	Route::get('questions/filter', 'QuestionController@filter')->name('questions.filter');
	Route::get('questions/basic', 'QuestionController@basic')->name('questions.basic');
	Route::resource('questions', 'QuestionController');

	Route::get('calls','CallController@index')->name('calls.index');
	Route::get('phonecontacts','PhonecontactController@index')->name('phonecontacts.index');

	Route::get('notes/filter', 'NoteController@filter')->name('notes.filter');
	Route::get('notes/create', 'NoteController@create')->name('notes.create');
	Route::get('notes', 'NoteController@index')->name('notes.index');
	Route::get('notes/{company}', 'NoteController@show')->name('notes.show');
	Route::post('notes', 'NoteController@store')->name('notes.store');
//	Route::get('notes/{user}/edit', 'NoteController@edit')->name('notes.edit');
//	Route::put('notes/{user}', 'NoteController@update')->name('notes.update');
	
});

Route::get('/{slug}', 'PageController@show')->name('pages.show');
	

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use App\Http\Controllers\Controller;
use App\User;
use App\Company;
use App\Basicquestionmaster;
use App\Question;
use App\Industry;
use App\Note;
use App\Legalstatus;
use App\Usagereason;
use Validator;
use Illuminate\Support\Facades\Auth;


class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
	 
	public function createXeroContact($id)
	{
		$company = Company::find($id);
		$company->createXeroContact();
		
	}
	 
    public function index()
    {
        $allCompanies = Company::All();
        $industries = Industry::All();
        $filter = ['fcompany'=>0,'findustry'=>0];
        $companies = Company::with(['industry','legalstatus','usagereason','user'])->paginate(10);
        return view('admin.companies.list', ['companies' => $companies, 'industries'=>$industries,'filter'=>$filter,'allCompanies' => $allCompanies]);
        
    }

    public function filter(Request $request)
    {
        $whereArray = [];
        if($request->fcompany > 0) {
               $whereArray[] = ['id','=',$request->fcompany];
        } 
        if($request->findustry > 0) {
               $whereArray[] = ['industry_id','=',$request->findustry];
        } 
        $companies = Company::with(['industry','legalstatus','usagereason','user'])->where($whereArray)->paginate(10);
                
        $allCompanies = Company::All();
        $industries = Industry::All();
        $filter = ['fcompany'=>$request->fcompany,'findustry'=>$request->findustry];
        return view('admin.companies.list', ['companies' => $companies, 'industries'=>$industries,'filter'=>$filter,'allCompanies' => $allCompanies]);
    }
    
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::whereDoesntHave('company')->where('role', '=', 'client')->get();
        $industries = Industry::orderBy('name')->get();
        $legalstatuses = Legalstatus::orderBy('name')->get();
        $usagereasons = Usagereason::orderBy('name')->get();
        return view('admin.companies.add', ['lookups'=>['users'=>$users,'industries'=>$industries,'legalstatuses' => $legalstatuses, 'usagereasons' => $usagereasons]]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $newcompany = new Company();
        
        $this->validate($request, $newcompany->getRules(), $newcompany->getMessages());
        
    
        $newcompany->fill($request->all());
        if ($newcompany->save()) {
				$newcompany->createXeroContact();
			
               $basics = Basicquestionmaster::All();
				foreach($basics as $basic) {
					$newQuestion = new Question();
					$newQuestion->company_id = $newcompany->id;
					$newQuestion->basic = true;
					$newQuestion->question = $basic->question;
					$newQuestion->category = $basic->category;
					$newQuestion->order = $basic->order;
					$newQuestion->save();
				}
				return redirect(route('admin.companies.show', ['id' => $newcompany->id]));
        } else {
            
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::with(['notes.updatedby' => function($query) { $query->select('id','first_name','last_name');}])->find($id);
        return view('admin.companies.show', ['company' => $company]);
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);
        $industries = Industry::orderBy('name')->get();
        $legalstatuses = Legalstatus::orderBy('name')->get();
        $usagereasons = Usagereason::orderBy('name')->get();
        return view('admin.companies.edit', ['company'=>$company,'lookups'=>['industries'=>$industries,'legalstatuses' => $legalstatuses, 'usagereasons' => $usagereasons]]);
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = Company::find($id);

		$editRules = [
//		'companyname' => 'required|max:180|unique:companies,companyname,' . $id, 
		'companyname' => 'required|max:180',
		'workemail' => 'email|max:180'
		];

        
        $this->validate($request, $editRules, $company->getMessages());
        
    
        $fields = ['companyname', 'companynumber','address1', 'address2','city', 'county','postcode','country','workemail','workphone', 'industry_id','legalstatus_id','usagereason_id', 'xero_id', 'webvisitorspermonth','callspermonth','averagesale' ];

        foreach ($fields as $field) {
               $company->$field = $request->$field;
        }
    
        if ($company->save()) {
               return redirect(route('admin.companies.show', ['id' => $company->id]));
        } else {
               return redirect(route('admin.companies.edit', ['id' => $company->id]));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
	

	
}

app/Http/Controllers/Clients/CompanyController.php
<?php

namespace App\Http\Controllers\Clients;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CompanyController extends Controller
{
    //
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use App\Company;
use App\Basicquestionmaster;
use App\Question;
use App\Industry;
use App\Legalstatus;
use App\Usagereason;
use Validator;

/**
 * Company Controller class
 *
 * Client controller to manage company records on the fontend application.
 * Clients can only create or update their own company record.
 */
class CompanyController extends Controller
{
    /**
     * Display company owned by current client.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect()->route('company.show', ['id' => Auth::user()->company->id]);
    }

    /**
     * Show the form for creating a new company.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // check that the user does  not have a company already
        if (Auth::user()->hasCompany()) {
               return redirect()->route('company.show', ['id' => Auth::user()->company->id])->with('status', ['class'=>'info','text'=>'You already have a company defined']);
        } else {
               $industries = Industry::orderBy('name')->get();
               $legalstatuses = Legalstatus::orderBy('name')->get();
               $usagereasons = Usagereason::orderBy('name')->get();
               return view('company.add', ['lookups'=>['industries'=>$industries,'legalstatuses' => $legalstatuses, 'usagereasons' => $usagereasons]]);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $newcompany = new Company();
        
        $this->validate($request, $newcompany->getRules(), $newcompany->getMessages());
        
    
        $newcompany->fill($request->all());
        $newcompany->user_id = Auth::user()->id;
        if ($newcompany->save()) {
				$newcompany->createXeroContact();
               // now get the basic questions
               $basics = Basicquestionmaster::All();
            foreach($basics as $basic) {
                $newQuestion = new Question();
                $newQuestion->company_id = $newcompany->id;
                $newQuestion->basic = true;
                $newQuestion->question = $basic->question;
                $newQuestion->category = $basic->category;
                $newQuestion->order = $basic->order;
                $newQuestion->save();
            }
            
               return redirect(route('company.show', ['id' => $newcompany->id]));
        } else {
            
        }
    }

    /**
     * Display the company record.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::find($id);
        return view('company.show', ['company' => $company]);
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/companies/add.blade.php
@extends('admin.layouts.app')

@section('title','Companies - Add New Company')

@section('content')
  <div class="col-md-12">
	<h3>Create new company</h3>

@if(count($errors)>0)
	<div class="alert alert-warning">Sorry but there are errors with this company; please correct them and ty to save again</div>
@endif

	<form id="create_company" class="form" action="{{ route('admin.companies.store') }}" method="post" role="form" style="display: block;">
		    {{ csrf_field() }}
			<div class="form-group @if($errors->has('user_id')) has-warning @endif">
				<label class="form-control-label col-sm-4"  for="user_id">User:</label>
				<div class="input-group col-sm-8 ">
					<select name="user_id" id="user_id" tabindex="3" class="form-control @if($errors->has('user_id')) form-control-warning @endif" >
						@foreach($lookups['users'] as $user)
							<option value="{{$user['id']}}" 
								@if (old('user_id') == $user['id']) ? selected @endif 
							>{{ $user['first_name']}} {{ $user['last_name']}}</option>
						@endforeach
					</select>
				</div>
			</div>
			<div class="form-group @if($errors->has('companyname')) has-warning @endif">
				<label class="form-control-label col-sm-4" for="companyname">Company Name:</label>
				<div class="input-group col-sm-8">
					<input type="text" name="companyname" id="companyname" tabindex="1" class="form-control @if($errors->has('companyname')) form-control-warning @endif" placeholder="Company Name" value="{{ old('company_name') }}" required>
				</div>
				@if($errors->has('companyname'))
						@foreach ($errors->get('companyname') as $message)
							<div class="offset-sm-4 col-sm-8 form-control-label"><span class="icon icon-thumbs-down"></span><strong>Oops! </strong>{{$message}}</div>
						@endforeach
				@endif
			</div>
			<div class="form-group @if($errors->has('companynumber')) has-warning @endif">
				<label class="form-control-label col-sm-4"  for="companynumber">Company Number:</label>
				<div class="input-group col-sm-8 form-inline">
					<input type="text" name="companynumber" id="companynumber" tabindex="2" class="form-control @if($errors->has('companynumber')) form-control-warning @endif" placeholder="012345678" value="{{ old('companynumber') }}" >
				</div>
					@if($errors->has('companynumber'))
							@foreach ($errors->get('companynumber') as $message)
								<div class="offset-sm-4 col-sm-8 form-control-label"><span class="icon icon-thumbs-down"></span><strong>Oops! </strong>{{$message}}</div>
							@endforeach
					@endif
			</div>
			<div class="form-group @if($errors->has('address1')) has-warning @endif">
				<label class="form-control-label col-sm-4"  for="address1">Address Line 1:</label>
				<div class="input-group col-sm-8 form-inline">
					<input type="text" name="address1" id="address1" tabindex="3" class="form-control @if($errors->has('address1')) form-control-warning @endif" placeholder="house name or number" value="">
				</div>
			</div>
			<div class="form-group @if($errors->has('address2')) has-warning @endif">
				<label class="form-control-label col-sm-4"  for="address2">Address Line 2:</label>
				<div class="input-group col-sm-8 form-inline">
					<input type="text" name="address2" id="address2" tabindex="3" class="form-control @if($errors->has('address1')) form-control-warning @endif" placeholder="street name" value="">
				</div>
			</div>
			<div class="form-group @if($errors->has('city')) has-warning @endif">

			<label class="form-control-label col-sm-4"  for="city">City:</label>
			<div class="input-group col-sm-8 form-inline">
				<input type="text" name="city" id="city" tabindex="3" class="form-control @if($errors->has('address2')) form-control-warning @endif" placeholder="city" value="">
			</div>
			</div>
			<div class="form-group @if($errors->has('county')) has-warning @endif">
			<label class="form-control-label col-sm-4"  for="county">County:</label>
			<div class="input-group col-sm-8 form-inline">
				<input type="text" name="county" id="county" tabindex="3" class="form-control @if($errors->has('address2')) form-control-warning @endif" placeholder="county" value="">
			</div>
			</div>
			<div class="form-group @if($errors->has('postcode')) has-warning @endif">
			<label class="form-control-label col-sm-4"  for="postcode">Postcode:</label>
			<div class="input-group col-sm-8 form-inline">
				<input type="text" name="postcode" id="postcode" tabindex="3" class="form-control @if($errors->has('postcode')) form-control-warning @endif" placeholder="AB1 10XY" value="">
			</div>
			</div>
			<div class="form-group @if($errors->has('country')) has-warning @endif">
			<label class="form-control-label col-sm-4"  for="country">Country:</label>
			<div class="input-group col-sm-8 form-inline">
				<input type="text" name="country" id="country" tabindex="3" class="form-control @if($errors->has('country')) form-control-warning @endif" placeholder="" value="UK">
			</div>
			</div>
			<div class="form-group @if($errors->has('workemail')) has-warning @endif">
			<label class="form-control-label col-sm-4"  for="workemail">Work EMail:</label>
			<div class="input-group col-sm-8 ">
				<input type="text" name="workemail" id="workemail" tabindex="3" class="form-control @if($errors->has('workemail')) form-control-warning @endif" placeholder="emal@work.com" value="{{ old('workemail') }}">
			</div>
			@if($errors->has('workemail'))
					@foreach ($errors->get('workemail') as $message)
						<div class="offset-sm-4 col-sm-8 form-control-label"><span class="icon icon-thumbs-down"></span><strong>Oops! </strong>{{$message}}</div>
					@endforeach
			@endif
			</div>
			<div class="form-group @if($errors->has('workphone')) has-warning @endif">
			<label class="form-control-label col-sm-4"  for="workphoe">Work Phone:</label>
			<div class="input-group col-sm-8 ">
				<input type="text" name="workphone" id="workphone" tabindex="3" class="form-control @if($errors->has('workphone')) form-control-warning @endif" placeholder="0207123456" value="{{ old('workphone') }}">
			</div>
			</div>
			<div class="form-group @if($errors->has('industry_id')) has-warning @endif">
			<label class="form-control-label col-sm-4"  for="industry_id">Industry:</label>
			<div class="input-group col-sm-8 ">
				<select name="industry_id" id="industry_id" tabindex="3" class="form-control @if($errors->has('industry')) form-control-warning @endif" >
					@foreach($lookups['industries'] as $industry)
						<option value="{{$industry['id']}}" 
							@if (old('industry_id') == $industry['id']) ? selected @endif 
						>{{ $industry['name']}}</option>
					@endforeach
				</select>
			</div>
			</div>
			<div class="form-group @if($errors->has('legalstatus_id')) has-warning @endif">
				<label class="form-control-label col-sm-4"  for="legalstatus_id">Legal Status:</label>
				<div class="input-group col-sm-8 ">
					<select name="legalstatus_id" id="legalstatus_id" tabindex="3" class="form-control @if($errors->has('legalstatus')) form-control-warning @endif" >
						@foreach($lookups['legalstatuses'] as $legalstatus)
							<option value="{{$legalstatus['id']}}" 
								@if (old('legalstatus_id') == $legalstatus['id']) ? selected @endif 
							>{{ $legalstatus['name']}}</option>
						@endforeach
					</select>
				</div>
			</div>
			<div class="form-group @if($errors->has('usagereason_id')) has-warning @endif">
			<label class="form-control-label col-sm-4"  for="usagereason_id">Usage Reason:</label>
			<div class="input-group col-sm-8 form-inline">
				<select name="usagereason_id" id="usagereason_id" tabindex="3" class="form-control @if($errors->has('usagereason')) form-control-warning @endif" >
					@foreach($lookups['usagereasons'] as $usagereason)
						<option value="{{$usagereason['id']}}" 
							@if (old('usagereason_id') == $usagereason['id']) ? selected @endif 
						>{{ $usagereason['name']}}</option>
					@endforeach
				</select>
			</div>
			</div>
			<div class="form-group @if($errors->has('xero_id')) has-warning @endif">
				<label class="col-sm-4 text-left"  for="xero_id">Xero Contact ID:</label>
				<div class="input-group col-sm-8 form-inline required">
					<input type="text" name="xero_id" id="xero_id" tabindex="3" class="form-control" placeholder="contact guid" value="{{ old('xero_id') }}">
				</div>
				@if($errors->has('xero_id'))
						@foreach ($errors->get('xero_id') as $message)
							<div class="offset-sm-4 col-sm-8 alert alert-warning"><span class="icon icon-thumbs-down"></span><strong>Oops! </strong>{{$message}}</div>
						@endforeach
				@endif
			</div>
			<div class="form-group @if($errors->has('webvisitorspermonth')) has-warning @endif">
				<label class="col-sm-4 text-left"  for="webvisitorspermonth">Web Visitors Per Month:</label>
				<div class="input-group col-sm-8 form-inline required">
					<input type="text" name="webvisitorspermonth" id="webvisitorspermonth" tabindex="3" class="form-control" placeholder="contact guid" value="{{ old('webvisitorspermonth') }}">
				</div>
				@if($errors->has('webvisitorspermonth'))
						@foreach ($errors->get('webvisitorspermonth') as $message)
							<div class="offset-sm-4 col-sm-8 alert alert-warning"><span class="icon icon-thumbs-down"></span><strong>Oops! </strong>{{$message}}</div>
						@endforeach
				@endif
			</div>
			<div class="form-group @if($errors->has('callspermonth')) has-warning @endif">
				<label class="col-sm-4 text-left"  for="callspermonth">Call Volume Per Month:</label>
				<div class="input-group col-sm-8 form-inline required">
					<input type="text" name="callspermonth" id="callspermonth" tabindex="3" class="form-control" placeholder="contact guid" value="{{ old('callspermonth') }}">
				</div>
				@if($errors->has('callspermonth'))
						@foreach ($errors->get('callspermonth') as $message)
							<div class="offset-sm-4 col-sm-8 alert alert-warning"><span class="icon icon-thumbs-down"></span><strong>Oops! </strong>{{$message}}</div>
						@endforeach
				@endif
			</div>
			<div class="form-group @if($errors->has('averagesale')) has-warning @endif">
				<label class="col-sm-4 text-left"  for="averagesale">Average Sale Value:</label>
				<div class="input-group col-sm-8 form-inline required">
					<input type="text" name="averagesale" id="averagesale" tabindex="3" class="form-control" placeholder="contact guid" value="{{ old('averagesale') }}">
				</div>
				@if($errors->has('averagesale'))
						@foreach ($errors->get('averagesale') as $message)
							<div class="offset-sm-4 col-sm-8 alert alert-warning"><span class="icon icon-thumbs-down"></span><strong>Oops! </strong>{{$message}}</div>
						@endforeach
				@endif
			</div>
			
		<br/>
		<div class="row">	
			<div class="col-sm-3 offset-sm-6">
				<input type="submit" name="addclient-submit" id="addclient-submit" tabindex="4" class="btn btn-login" value="Save">
			</div>
		</div>
	</form>

  
  </div>
@endsection

resources/views/admin/companies/list.blade.php
@extends('admin.layouts.app')

@section('title','Company Management')

@section('content')

<div class="container">
		<div class="toolbar">
			<div class="btn-group dashhead-toolbar-item">
				  <a title="Add New Company" type="button" class="btn btn-outline-primary" href="{{route('admin.companies.create')}}">
					<span class="icon icon-add-to-list"></span> New Company
				  </a>
			</div>
			<form id="company_filter" class="form form-navbar" action="{{ route('admin.companies.filter') }}" method="post" role="form" style="display: block;">
					{{ csrf_field() }}
			<div class="dashhead-toolbar-item form-group">		
				<select name="fcompany" id="fcompany" class="form-control">
					<option value="0">Any Company</option>
					@foreach($allCompanies as $company)
					<option value="{{$company->id}}"  
						@if($filter['fcompany'] == $company->id) 
							selected
						@endif 
					>{{$company->getRef()}} - {{$company->companyname}}</option>
					@endforeach
				</select>
			</div>
			<div class="dashhead-toolbar-item form-group">		
				<select name="findustry" id="findustry" class="form-control">
					<option value="0">Any Industry</option>
					@foreach($industries as $industry)
						<option value="{{$industry->id}}"  @if($filter['findustry'] == $industry->id) selected @endif   >{{$industry->name}}</option>
					@endforeach
				</select>
			</div>
			<div class="btn-group dashhead-toolbar-item">
					<button type="submit" name="filtercompany-submit" id="filtercompany-submit" tabindex="4" class="btn btn-outline-primary"> 
					<span class="icon icon-funnel"></span> Filter</button>
			</div>
			</form>		
		</div>
</div>



<div class="col-md-12">
<div class="row">
	<div class="col-sm-8">
	 {{ $companies->links() }}
	</div>
</div>
<div class="row">
	<div>
	<table id="companyTable" class="table table-responsive" data-sort="table">
		<thead>
			<tr>
				<th class="header">Edit Client</th>
				<th class="header">Client Name</th>
				<th class="header">Edit Company</th>
				<th class="header">Company Name</th>
				<th class="header">Company Services</th>
				<th class="header">Industry</th>
				<th class="header">Legal Status</th>
				<th class="header">Usage Reason</th>
			</tr>
		</thead>
	<tbody>
	@foreach($companies as $company)
	<tr>
		<td class="text-left"><a title="Edit User" href="{{route('admin.users.edit',['id' => $company['user']['id']])}}"><span class="icon icon-edit"></a></td>
		<td><a href="{{route('admin.users.show',['id'=>$company['user']['id']])}}">{{$company['user']['first_name']}}&nbsp;{{$company['user']['last_name']}}</a></td>
		<td class="text-left"><a title="Edit Company" href="{{route('admin.companies.edit',['id' => $company['id']])}}"><span class="icon icon-edit"></a></td>
		<td><a href="{{route('admin.companies.show',['id'=>$company['id']])}}">{{$company->getRef()}} - {{$company['companyname']}}</a></td>
		<td>{{$company->companyservices()->count()}}</td>
		<td>{{$company['industry']['name']}}</td>
		<td>{{$company['legalstatus']['name']}}</td>
		<td>{{$company['usagereason']['name']}}</td>
	</tr>
	@endforeach
	</tbody>
	</table>
	</div>
</div>
<div class="row">
	<div class="offset-col-8 col-sm-4">
	{{ $companies->links() }}
	</div>
</div>
</div>
@endsection

@section('addscripts')
<script>
	$(document).ready(function() 
		{ 
			$("#companyTable").tablesorter(); 
		} 
	); 

</script>
@endsection