routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
Route::get('/privacy', function () {
    return view('legals');
});

Route::get('/terms', function () {
    return view('tsandcs');
});
*/

Auth::routes();
Route::get('/admin', 'Admin\\DashboardController@index')->name('admin.dashboard');
Route::get('/admin/login', 'Admin\\Auth\\LoginController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Admin\\Auth\\LoginController@login')->name('admin.login');
Route::post('/admin/logout', 'Admin\\Auth\\LoginController@logout')->name('admin.logout');
Route::get('/pages/{slug}', 'PageController@show')->name('pages.show');

// Client routes
Route::group(['middleware' => ['auth','active','client']], function()
{
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/questions/basic', 'QuestionController@basic')->name('questions.basic');
	Route::get('/questions/faq', 'QuestionController@faq')->name('questions.faq');
	Route::resource('company', 'CompanyController');
	Route::resource('questions', 'QuestionController');
	Route::resource('services', 'CompanyServicesController');
});

// Admin routes
Route::group(['middleware' => ['auth','active','admin'], 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function()
{
	Route::get('users/create', 'UserController@create')->name('users.create');
	Route::post('users', 'UserController@store')->name('users.store');
	Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
	Route::put('users/{user}', 'UserController@update')->name('users.update');

	Route::get('companies/create', 'CompanyController@create')->name('companies.create');
	Route::post('companies', 'CompanyController@store')->name('companies.store');
	Route::get('companies/{user}/edit', 'CompanyController@edit')->name('companies.edit');
	Route::put('companies/{user}', 'CompanyController@update')->name('companies.update');

	Route::get('alerts', 'AlertController@index')->name('alerts.index');
	Route::get('alerts/create', 'AlertController@create')->name('alerts.create');
	Route::get('alerts/{id}', 'AlertController@show')->name('alerts.show');
	Route::post('alerts', 'AlertController@store')->name('alerts.store');
	Route::get('alerts/{id}/edit', 'AlertController@edit')->name('alerts.edit');
	Route::put('alerts/{id}', 'AlertController@update')->name('alerts.update');
	
	
	
	
//	Route::resource('users', 'UserController');
//	Route::resource('companies', 'CompanyController');
	Route::resource('servicecategories', 'ServicecategoryController');
	Route::resource('services', 'ServiceController');
//	Route::resource('companyservices', 'CompanyServicesController');
	Route::post('bills/getservices', 'BillController@getServices')->name('bills.getservices');
	Route::post('bills/filter', 'BillController@filter')->name('bills.filter');
	Route::get('bills/createallbills', 'BillController@createAllBills')->name('bills.createallbills');
	Route::get('bills/saveallbills/{year}/{month}', 'BillController@saveAllBills')->name('bills.saveallbills');
	Route::get('bills/exportbills/{year}/{month}', 'BillController@export')->name('bills.export');
	Route::resource('bills', 'BillController');

	Route::resource('queues', 'QueueController');
	Route::get('queues/company/{company_id}', 'QueueController@company')->name('queues.company');

	Route::post('company/filter', 'CompanyController@filter')->name('companies.filter');
	Route::post('companyservices/filter', 'CompanyServicesController@filter')->name('companyservices.filter');
	Route::resource('webchats', 'WebchatController');
	Route::resource('basicquestionmasters', 'BasicquestionmasterController');

	Route::resource('pages', 'PageController');
	Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

	

});



/* Staff  */
Route::group(['middleware' => ['auth','active','staff'], 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function()
{
	Route::get('users', 'UserController@index')->name('users.index');
	Route::get('users/{user}', 'UserController@show')->name('users.show');

	Route::get('companies', 'CompanyController@index')->name('companies.index');
	Route::get('companies/{company}', 'CompanyController@show')->name('companies.show');

	Route::get('companyservices/create', 'CompanyServicesController@create')->name('companyservices.create');
	Route::get('companyservices', 'CompanyServicesController@index')->name('companyservices.index');
	Route::get('companyservices/{company}', 'CompanyServicesController@show')->name('companyservices.show');
	Route::post('companyservices', 'CompanyServicesController@store')->name('companyservices.store');
	Route::get('companyservices/{user}/edit', 'CompanyServicesController@edit')->name('companyservices.edit');
	Route::put('companyservices/{user}', 'CompanyServicesController@update')->name('companyservices.update');

	Route::get('questions/filter', 'QuestionController@filter')->name('questions.filter');
	Route::get('questions/basic', 'QuestionController@basic')->name('questions.basic');
	Route::resource('questions', 'QuestionController');

	Route::get('calls','CallController@index')->name('calls.index');
	Route::get('phonecontacts','PhonecontactController@index')->name('phonecontacts.index');

	Route::get('notes/filter', 'NoteController@filter')->name('notes.filter');
	Route::get('notes/create', 'NoteController@create')->name('notes.create');
	Route::get('notes', 'NoteController@index')->name('notes.index');
	Route::get('notes/{company}', 'NoteController@show')->name('notes.show');
	Route::post('notes', 'NoteController@store')->name('notes.store');
//	Route::get('notes/{user}/edit', 'NoteController@edit')->name('notes.edit');
//	Route::put('notes/{user}', 'NoteController@update')->name('notes.update');
	
});

Route::get('/{slug}', 'PageController@show')->name('pages.show');
	

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use App\Http\Controllers\Controller;
use App\User;
use App\Company;
use App\Basicquestionmaster;
use App\Question;
use App\Industry;
use App\Note;
use App\Legalstatus;
use App\Usagereason;
use Validator;
use Illuminate\Support\Facades\Auth;


class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
	 
	public function createXeroContact($id)
	{
		$company = Company::find($id);
		$company->createXeroContact();
		
	}
	 
    public function index()
    {
        $allCompanies = Company::All();
        $industries = Industry::All();
        $filter = ['fcompany'=>0,'findustry'=>0];
        $companies = Company::with(['industry','legalstatus','usagereason','user'])->paginate(10);
        return view('admin.companies.list', ['companies' => $companies, 'industries'=>$industries,'filter'=>$filter,'allCompanies' => $allCompanies]);
        
    }

    public function filter(Request $request)
    {
        $whereArray = [];
        if($request->fcompany > 0) {
               $whereArray[] = ['id','=',$request->fcompany];
        } 
        if($request->findustry > 0) {
               $whereArray[] = ['industry_id','=',$request->findustry];
        } 
        $companies = Company::with(['industry','legalstatus','usagereason','user'])->where($whereArray)->paginate(10);
                
        $allCompanies = Company::All();
        $industries = Industry::All();
        $filter = ['fcompany'=>$request->fcompany,'findustry'=>$request->findustry];
        return view('admin.companies.list', ['companies' => $companies, 'industries'=>$industries,'filter'=>$filter,'allCompanies' => $allCompanies]);
    }
    
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::whereDoesntHave('company')->where('role', '=', 'client')->get();
        $industries = Industry::orderBy('name')->get();
        $legalstatuses = Legalstatus::orderBy('name')->get();
        $usagereasons = Usagereason::orderBy('name')->get();
        return view('admin.companies.add', ['lookups'=>['users'=>$users,'industries'=>$industries,'legalstatuses' => $legalstatuses, 'usagereasons' => $usagereasons]]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $newcompany = new Company();
        
        $this->validate($request, $newcompany->getRules(), $newcompany->getMessages());
        
    
        $newcompany->fill($request->all());
        if ($newcompany->save()) {
				$newcompany->createXeroContact();
			
               $basics = Basicquestionmaster::All();
				foreach($basics as $basic) {
					$newQuestion = new Question();
					$newQuestion->company_id = $newcompany->id;
					$newQuestion->basic = true;
					$newQuestion->question = $basic->question;
					$newQuestion->category = $basic->category;
					$newQuestion->order = $basic->order;
					$newQuestion->save();
				}
				return redirect(route('admin.companies.show', ['id' => $newcompany->id]));
        } else {
            
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::with(['notes.updatedby' => function($query) { $query->select('id','first_name','last_name');}])->find($id);
        return view('admin.companies.show', ['company' => $company]);
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);
        $industries = Industry::orderBy('name')->get();
        $legalstatuses = Legalstatus::orderBy('name')->get();
        $usagereasons = Usagereason::orderBy('name')->get();
        return view('admin.companies.edit', ['company'=>$company,'lookups'=>['industries'=>$industries,'legalstatuses' => $legalstatuses, 'usagereasons' => $usagereasons]]);
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = Company::find($id);

		$editRules = [
//		'companyname' => 'required|max:180|unique:companies,companyname,' . $id, 
		'companyname' => 'required|max:180',
		'workemail' => 'email|max:180'
		];

        
        $this->validate($request, $editRules, $company->getMessages());
        
    
        $fields = ['companyname', 'companynumber','address1', 'address2','city', 'county','postcode','country','workemail','workphone', 'industry_id','legalstatus_id','usagereason_id', 'xero_id', 'webvisitorspermonth','callspermonth','averagesale' ];

        foreach ($fields as $field) {
               $company->$field = $request->$field;
        }
    
        if ($company->save()) {
               return redirect(route('admin.companies.show', ['id' => $company->id]));
        } else {
               return redirect(route('admin.companies.edit', ['id' => $company->id]));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
	

	
}

app/Http/Controllers/Clients/CompanyController.php
<?php

namespace App\Http\Controllers\Clients;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CompanyController extends Controller
{
    //
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use App\Company;
use App\Basicquestionmaster;
use App\Question;
use App\Industry;
use App\Legalstatus;
use App\Usagereason;
use Validator;

/**
 * Company Controller class
 *
 * Client controller to manage company records on the fontend application.
 * Clients can only create or update their own company record.
 */
class CompanyController extends Controller
{
    /**
     * Display company owned by current client.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect()->route('company.show', ['id' => Auth::user()->company->id]);
    }

    /**
     * Show the form for creating a new company.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // check that the user does  not have a company already
        if (Auth::user()->hasCompany()) {
               return redirect()->route('company.show', ['id' => Auth::user()->company->id])->with('status', ['class'=>'info','text'=>'You already have a company defined']);
        } else {
               $industries = Industry::orderBy('name')->get();
               $legalstatuses = Legalstatus::orderBy('name')->get();
               $usagereasons = Usagereason::orderBy('name')->get();
               return view('company.add', ['lookups'=>['industries'=>$industries,'legalstatuses' => $legalstatuses, 'usagereasons' => $usagereasons]]);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $newcompany = new Company();
        
        $this->validate($request, $newcompany->getRules(), $newcompany->getMessages());
        
    
        $newcompany->fill($request->all());
        $newcompany->user_id = Auth::user()->id;
        if ($newcompany->save()) {
				$newcompany->createXeroContact();
               // now get the basic questions
               $basics = Basicquestionmaster::All();
            foreach($basics as $basic) {
                $newQuestion = new Question();
                $newQuestion->company_id = $newcompany->id;
                $newQuestion->basic = true;
                $newQuestion->question = $basic->question;
                $newQuestion->category = $basic->category;
                $newQuestion->order = $basic->order;
                $newQuestion->save();
            }
            
               return redirect(route('company.show', ['id' => $newcompany->id]));
        } else {
            
        }
    }

    /**
     * Display the company record.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::find($id);
        return view('company.show', ['company' => $company]);
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/company/list.blade.php
@extends('layouts.app')

@section('title','Company Management')

@section('content')
 <div class="col-md-12">
<div class="row">
	<div class="col-sm-8">
	 {{ $companies->links() }}
	</div>
	<div class="col-sm-4 pull-right">
		<div class="btn-group">
			  <a title="Add New Company" type="button" class="btn btn-outline-primary" href="{{route('company.create')}}">
				<span class="icon icon-add-to-list"></span> New Company
			  </a>
		</div>
	</div>
</div>
<div class="row">
	<div class="table-responsive">
	<table id="companyTable" class="table" data-sort="table">
		<thead>
			<tr>
				<th class="header">Client Name</th>
				<th class="header">Company Name</th>
				<th class="header">Industry</th>
				<th class="header">Legal Status</th>
				<th class="header">Usage Reason</th>
				<th class="header">Xero ID</th>
			</tr>
		</thead>
	<tbody>
	@foreach($companies as $company)
	<tr>
		<td><a href="{{route('admin.users.show',['id'=>$company['user']['id']])}}">{{$company['user']['first_name']}}&nbsp;{{$company['user']['last_name']}}</a></td>
		<td><a href="{{route('admin.companies.show',['id'=>$company['id']])}}">{{$company['companyname']}}</a></td>
		<td>{{$company['industry']['name']}}</td>
		<td>{{$company['legalstatus']['name']}}</td>
		<td>{{$company['usagereason']['name']}}</td>
		<td>{{$company['xero_id']}}</td>
	</tr>
	@endforeach
	</tbody>
	</table>
	</div>
</div>
<div class="row">
	<div class="offset-col-8 col-sm-4">
	{{ $companies->links() }}
	</div>
</div>
</div>
@endsection

@section('addscripts')
<script>
	$(document).ready(function() 
		{ 
			$("#companyTable").tablesorter(); 
		} 
	); 

</script>
@endsection

resources/views/company/show.blade.php
@extends('layouts.app')

@section('title','Company Details')

@section('content')
<div class="col-md-12">

	<div class="row">
		<div class="btn-group">
			  <a title="Company List" type="button" class="btn btn-outline-primary" href="{{route('company.index')}}">
				<span class="icon icon-list"></span>
			  </a>
			  <a title="Edit" type="button" class="btn btn-outline-primary" href="{{route('company.edit',['id'=>$company['id']])}}">
				<span class="icon icon-edit"></span>
			  </a>
		</div>
	</div>

	  <div class="panel panel-default">
			<div class="panel-heading">
			  <h4 class="panel-title">
				Company Details: {{str_pad($company->id,4,0,STR_PAD_LEFT)}} - {{$company->companyname}}
				<a data-toggle="collapse" href="#company"><span class="icon icon-chevron-down"></span></a>
			  </h4>
			</div>
			<div id="company" class="panel-collapse collapse in">
			  <div class="panel-body">
				<div class="row">
					<div class="col-sm-6">
						<address>
							{{$company->address1}}<br/>
							{{$company->address2}}<br/>
							{{$company->city}}, {{$company->county}}<br/>
							{{$company->postcode}}, {{$company->country}}
						</address>
						<address>
							<span class="icon icon-email"></span> {{$company->workemail}}
							<span class="icon icon-phone"></span> {{$company->workphone}}
						</address>
					</div>
					<div class="col-sm-6">
						<div>Company Number: {{$company->companynumber}}</div>
						<div>Xero ID: {{$company->xero_id}}</div>
						<div>Industry: {{$company->industry->name}}</div>
						<div>Usage Reason: {{$company->usagereason->name}}</div>
						<div>Services
							<ul>
								<li>Web Visitors: {{$company->webvisitorspermonth}}</li>
								<li>Call Volume per month: {{$company->callspermonth}}</li>
								<li>Average Sale: {{$company->averagesale}}</li>
							</ul>
						</div>
					</div>
				</div>
			  </div>
				<div class="panel-footer">
					Client: {{$company->user->first_name}} {{$company->user->last_name}}
				</div>
		   </div>
	  </div>
	  

	  <div class="panel panel-default">
		<div class="panel-heading">
		  <h4 class="panel-title">
			Company Services <span class="badge badge-info">{{$company->companyservices->count()}}</span>
			<a data-toggle="collapse" href="#companyservices"><span class="icon icon-chevron-down"></span>more..</a>
		  </h4>
		</div>
		<div id="companyservices" class="panel-collapse collapse">
		  <div class="panel-body">
			<ul class="list-unstyled">
			@foreach($company->companyservices as $companyservice)
				<li class="">
					<div class="panel">
						<div class="panel-heading">
							<h4 class="panel-title">
								{{$companyservice->service->name}} 
								@if($companyservice->widget_id)
								<button type="button" class="btn btn-info" onclick="showCode('{{$companyservice->widget_id}}')">Show code</button>
								@endif
								@if($companyservice->webchats->count() > 0)
									<span class="badge badge-default">Webchats {{$companyservice->webchats->count()}}</span>
									<a data-toggle="collapse" href="#companyservices-{{$companyservice->id}}"><span class="icon icon-chevron-down"></span>more..</a>
								@endif	
								@if($companyservice->queues->count() > 0)
									<span class="badge badge-default">Queues {{$companyservice->queues->count()}}</span>
									<a data-toggle="collapse" href="#companyservices-{{$companyservice->id}}"><span class="icon icon-chevron-down"></span></a>
								@endif
							</h4>
							
						</div>
						@if($companyservice->webchats->count() > 0)
						<div id="companyservices-{{$companyservice->id}}" class="panel-collapse collapse">
							<div class="panel-body">
									<ul class="list-unstyled">
										@foreach($companyservice->webchats as $webchat)
											<li>Requester: {{$webchat->requester_details_name}}, Date: {{$webchat->created_at_date}}</li>
										@endforeach
									</ul>
							</div>
						 </div>
						@endif
						@if($companyservice->queues->count() > 0)
						<div id="companyservices-{{$companyservice->id}}" class="panel-collapse collapse">
							<div class="panel-body">
									<ul class="list-unstyled">
										@foreach($companyservice->queues as $queue)
											<li>
												<div class="well row">	
													<h5 class="col-sm-2">Queue: {{$queue->queueid}} / {{$queue->queuename}}	<span class="label label-default">{{$queue->type}}</span></h5>
													<div class="col-sm-2">Date: {{$queue->date}}</div>
													<div class="col-sm-4">Phone Number(s): {{$queue->phonenumbers}}</div>
													<div class="col-sm-4">Number Presentation: {{$queue->numberpresentation}}</div>
													<div class="col-sm-12">Notes: {{$queue->notes}}</div>
												</div>
											</li>
										@endforeach
									</ul>
							</div>
						 </div>
						@endif
					</div>
				</li>
			@endforeach
			</ul>
		  </div>
		</div>
	  </div>
	  <div class="panel panel-default">
		<div class="panel-heading">
		  <h4 class="panel-title">
			Company Questions <span class="badge badge-info">{{$company->questions->count()}}</span>
			<a data-toggle="collapse" href="#questions"><span class="icon icon-chevron-down"></span>more..</a>
		  </h4>
		</div>
		<div id="questions" class="panel-collapse collapse">
		  <div class="panel-body">
			<ul class="list-group">
			@foreach($company->questions as $question)
				<li class="list-group-item">
					<h5 class="list-group-item-heading">Q: {{$question->question}}	<span class="label label-default">{{$question->category}}</span></h5>
					<p class="list-group-item-text">A: {{$question->answer}}</p>
				</li>
			@endforeach
			</ul>
		  </div>
		</div>
	  </div>

 
</div>

<div id="webchatCode" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Webchat Code</h4>
      </div>
      <div class="modal-body">
        <p>Insert this code into your web page.</p>
		<pre id="modalCode"></pre>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

@endsection

@section('addscripts')
<script>

function showCode(webchatid) {
	modalCode = "&lt;!-- begin Handlr code --&gt;\r\n";
	modalCode += "&lt;script type=&quot;text/javascript&quot;&gt;\r\n";
	modalCode += "(function() {\r\n";
	modalCode += "    var se = document.createElement('script'); se.type = &quot;text/javascript&quot;; se.async = true;\r\n";
	modalCode += "    se.src = '//storage.googleapis.com/handlrchat/js/" + webchatid + ".js';\r\n";
	modalCode += "    var done = false;\r\n";
	modalCode += "	  se.onload = se.onreadystatechange = function() {\r\n";
	modalCode += "         if (!done&amp;&amp;(!this.readyState||this.readyState==='loaded'||this.readyState==='complete')) {\r\n";
	modalCode += "				done = true;\r\n";
	modalCode += "         }\r\n";
	modalCode += "    };\r\n";
	modalCode += "	  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(se, s);\r\n";
	modalCode += "})();\r\n";
	modalCode += "&lt;/script&gt;\r\n";
	modalCode += "&lt;!-- end Handlr code --&gt;\r\n";

	$("#modalCode").html(modalCode);
	$("#webchatCode").modal("show");
	
}

</script>


@endsection