routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
Route::get('/privacy', function () {
    return view('legals');
});

Route::get('/terms', function () {
    return view('tsandcs');
});
*/

Auth::routes();
Route::get('/admin', 'Admin\\DashboardController@index')->name('admin.dashboard');
Route::get('/admin/login', 'Admin\\Auth\\LoginController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Admin\\Auth\\LoginController@login')->name('admin.login');
Route::post('/admin/logout', 'Admin\\Auth\\LoginController@logout')->name('admin.logout');
Route::get('/pages/{slug}', 'PageController@show')->name('pages.show');

// Client routes
Route::group(['middleware' => ['auth','active','client']], function()
{
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/questions/basic', 'QuestionController@basic')->name('questions.basic');
	Route::get('/questions/faq', 'QuestionController@faq')->name('questions.faq');
	Route::resource('company', 'CompanyController');
	Route::resource('questions', 'QuestionController');
	Route::resource('services', 'CompanyServicesController');
});

// Admin routes
Route::group(['middleware' => ['auth','active','admin'], 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function()
{
	Route::get('users/create', 'UserController@create')->name('users.create');
	Route::post('users', 'UserController@store')->name('users.store');
	Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
	Route::put('users/{user}', 'UserController@update')->name('users.update');

	Route::get('companies/create', 'CompanyController@create')->name('companies.create');
	Route::post('companies', 'CompanyController@store')->name('companies.store');
	Route::get('companies/{user}/edit', 'CompanyController@edit')->name('companies.edit');
	Route::put('companies/{user}', 'CompanyController@update')->name('companies.update');

	Route::get('alerts', 'AlertController@index')->name('alerts.index');
	Route::get('alerts/create', 'AlertController@create')->name('alerts.create');
	Route::get('alerts/{id}', 'AlertController@show')->name('alerts.show');
	Route::post('alerts', 'AlertController@store')->name('alerts.store');
	Route::get('alerts/{id}/edit', 'AlertController@edit')->name('alerts.edit');
	Route::put('alerts/{id}', 'AlertController@update')->name('alerts.update');
	
	
	
	
//	Route::resource('users', 'UserController');
//	Route::resource('companies', 'CompanyController');
	Route::resource('servicecategories', 'ServicecategoryController');
	Route::resource('services', 'ServiceController');
//	Route::resource('companyservices', 'CompanyServicesController');
	Route::post('bills/getservices', 'BillController@getServices')->name('bills.getservices');
	Route::post('bills/filter', 'BillController@filter')->name('bills.filter');
	Route::get('bills/createallbills', 'BillController@createAllBills')->name('bills.createallbills');
	Route::get('bills/saveallbills/{year}/{month}', 'BillController@saveAllBills')->name('bills.saveallbills');
	Route::get('bills/exportbills/{year}/{month}', 'BillController@export')->name('bills.export');
	Route::resource('bills', 'BillController');

	Route::resource('queues', 'QueueController');
	Route::get('queues/company/{company_id}', 'QueueController@company')->name('queues.company');

	Route::post('company/filter', 'CompanyController@filter')->name('companies.filter');
	Route::post('companyservices/filter', 'CompanyServicesController@filter')->name('companyservices.filter');
	Route::resource('webchats', 'WebchatController');
	Route::resource('basicquestionmasters', 'BasicquestionmasterController');

	Route::resource('pages', 'PageController');
	Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

	

});



/* Staff  */
Route::group(['middleware' => ['auth','active','staff'], 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function()
{
	Route::get('users', 'UserController@index')->name('users.index');
	Route::get('users/{user}', 'UserController@show')->name('users.show');

	Route::get('companies', 'CompanyController@index')->name('companies.index');
	Route::get('companies/{company}', 'CompanyController@show')->name('companies.show');

	Route::get('companyservices/create', 'CompanyServicesController@create')->name('companyservices.create');
	Route::get('companyservices', 'CompanyServicesController@index')->name('companyservices.index');
	Route::get('companyservices/{company}', 'CompanyServicesController@show')->name('companyservices.show');
	Route::post('companyservices', 'CompanyServicesController@store')->name('companyservices.store');
	Route::get('companyservices/{user}/edit', 'CompanyServicesController@edit')->name('companyservices.edit');
	Route::put('companyservices/{user}', 'CompanyServicesController@update')->name('companyservices.update');

	Route::get('questions/filter', 'QuestionController@filter')->name('questions.filter');
	Route::get('questions/basic', 'QuestionController@basic')->name('questions.basic');
	Route::resource('questions', 'QuestionController');

	Route::get('calls','CallController@index')->name('calls.index');
	Route::get('phonecontacts','PhonecontactController@index')->name('phonecontacts.index');

	Route::get('notes/filter', 'NoteController@filter')->name('notes.filter');
	Route::get('notes/create', 'NoteController@create')->name('notes.create');
	Route::get('notes', 'NoteController@index')->name('notes.index');
	Route::get('notes/{company}', 'NoteController@show')->name('notes.show');
	Route::post('notes', 'NoteController@store')->name('notes.store');
//	Route::get('notes/{user}/edit', 'NoteController@edit')->name('notes.edit');
//	Route::put('notes/{user}', 'NoteController@update')->name('notes.update');
	
});

Route::get('/{slug}', 'PageController@show')->name('pages.show');
	

app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    use \App\Traits\Userstamps;
    private $rules = [
    'message' => 'required|max:500',
	'company_id' => 'required'
    ];
                    
    private    $messages = [
    ];
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'message','company_id','date'
    ];

    public function company()
    {
        return $this->belongsTo('App\Company');
    }

    
    public function getRules() 
    {
        return $this->rules;
    }

    public function getMessages() 
    {
        return $this->messages;
    }

    public function createdby() 
    {
        return $this->belongsTo('App\User', 'created_by', 'id');
    }

    public function updatedby() 
    {
        return $this->belongsTo('App\User', 'updated_by', 'id');
    }

    //
}

app/Http/Controllers/Admin/NoteController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Note;
use Validator;
use App\Company;


class NoteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $allCompanies = Company::All();
        $notes = Note::with(['company'])->paginate(10);
        $filter = ['fcompany'=>0];
        return view('admin.notes.list', ['notes' => $notes, 'allCompanies' => $allCompanies, 'filter'=>$filter]);
    }

    public function filter(Request $request)
    {
		$company = 0;
        $whereArray = [];
		if ($request->has("company")) {
			$company_id =  ltrim($request->company, '0');
			if($company_id > 0) {
				   $whereArray[] = ['company_id','=',$company_id];
			} 
		} 
        $notes = Note::with(['company'])->where($whereArray)->paginate(10);
                
        $allCompanies = Company::All();
        $filter = ['fcompany'=>$request->fcompany];
        return view('admin.notes.list', ['notes' => $notes,'filter'=>$filter,'allCompanies' => $allCompanies]);
    }
	
	
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::All();
        return view('admin.notes.add', ['companies'=>$companies]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $newnote = new Note();
        
        $this->validate($request, $newnote->getRules(), $newnote->getMessages());
        
    
        $newnote->fill($request->all());
        if ($newnote->save()) {
				if($request->ajax()) {
					return json_encode($newnote->id);
				} else {
					return redirect(route('admin.notes.show', ['id' => $newnote->id]));
				}
        } else {
            
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $note = note::find($id);
        return view('admin.notes.show', ['note' => $note]);
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     *
    public function edit($id)
    {
        $companies = Company::All();
        $note = Note::find($id);
        return view('admin.notes.edit', ['note'=>$note, 'companies'=>$companies]);
    }
	*/

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     * @return \Illuminate\Http\Response
     *
    public function update(Request $request, $id)
    {
        $note = Note::find($id);
        

        $editrules = [
        'note' => 'required|max:180'
        ];
        
        $this->validate($request, $editrules, $note->getMessages());
    
        $fields = ['date','message','company_id' ];

        foreach ($fields as $field) {
               $note->$field = $request->$field;
        }

    
        if ($note->save()) {
               return redirect(route('admin.notes.show', ['id' => $note->id]));
        } else {
               return redirect(route('admin.notes.edit', ['id' => $note->id]));
        }
    }
	*/
	

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     *
    public function destroy($id)
    {
        //
    }
    //
	*/


}

resources/views/admin/notes/add.blade.php
@extends('admin.layouts.app')

@section('title','Add New Note')

@section('content')
  <div class="col-md-12">
	<h3>Create new Note</h3>

@if(count($errors)>0)
	<div class="alert alert-warning">Sorry but there are errors with this note; please correct them and ty to save again</div>
@endif
 <div class="btn-group">
      <a title="Note List" type="button" class="btn btn-outline-primary" href="{{route('admin.notes.index')}}">
        <span class="icon icon-list"></span>
      </a>
</div>

	<form id="create_note" class="form" action="{{ route('admin.notes.store') }}" method="post" role="form" style="display: block;">
		    {{ csrf_field() }}
		<div class="form-group @if($errors->has('company_id')) has-warning @endif">
			<label class="form-control-label col-sm-4" for="company_id">Company:</label>
			<div class="col-sm-8 input-group">
			<select name="company_id" id="company_id" tabindex="3" class="form-control" >
				@foreach($companies as $company)
				<option value="{{$company['id']}}" @if (old('company_id') ==$company['id']) ? selected @endif >{{$company['companyname']}}</option>
				@endforeach
			</select>
			</div>
		</div>
		<div class="form-group @if($errors->has('message')) has-warning @endif">
			<label class="form-control-label col-sm-4" for="message">Note:</label>
			<div class="input-group col-sm-8">
				<input type="text" name="message" id="message" tabindex="1" class="form-control" placeholder="my note" value="{{ old('message') }}" required>
			</div>
			@if($errors->has('message'))
					@foreach ($errors->get('note') as $message)
						<div class="offset-sm-4 col-sm-8 alert alert-warning"><span class="icon icon-thumbs-down"></span><strong>Oops! </strong>{{$message}}</div>
					@endforeach
			@endif
		</div>
		<br/>
		<div class="col-sm-3 offset-sm-6">
			<input type="submit" name="addnote-submit" id="addnote-submit" tabindex="4" class="btn btn-login" value="Save">
		</div>
	</form>

  
  </div>
@endsection

resources/views/admin/notes/edit.blade.php
@extends('admin.layouts.app')

@section('title','Edit Note')

@section('content')
  <div class="col-md-12">

@if(count($errors)>0)
	<div class="alert alert-warning">Sorry but there are errors with this note; please correct them and ty to save again</div>
@endif

	<form id="create_note" class="form" action="{{ route('admin.notes.update',['id' => $note->id]) }}" method="post" role="form" style="display: block;">
		    {{ csrf_field() }}
			{{ method_field('PUT') }}
		<div class="form-group @if($errors->has('company_id')) has-warning @endif">
			<label class="form-control-label col-sm-4" for="company_id">Company:</label>
			<div class="col-sm-8 input-group">
			<select name="company_id" id="company_id" tabindex="3" class="form-control" >
				@foreach($companies as $company)
				<option value="{{$company->id}}" 
					@if ($note->company_id == $company->id)
						selected 
					@endif 
				>{{$company->companyname}}</option>
				@endforeach
			</select>
			</div>
		</div>
		<br/>
		<div class="col-sm-3 offset-sm-6">
				<input type="submit" name="editbasiccategorymaster-submit" id="editbasiccategorymaster-submit" tabindex="4" class="btn btn-login" value="Save">
		</div>
	</form>

  
  </div>
@endsection

resources/views/admin/notes/list.blade.php
@extends('admin.layouts.app')

@section('title','Company Notes')

@section('content')
<div class="btn-group">
	  <a title="Add new note" type="button" class="btn btn-outline-primary" href="{{route('admin.notes.create')}}">
		<span class="icon icon-pencil"></span>
	  </a>
</div>

<div class="container">
		<div class="dashhead-toolbar">
			<form id="filter-notes" class="form form-navbar" action="{{ route('admin.notes.filter') }}" method="get" role="form" style="display: block;">
			<div class="dashhead-toolbar-item form-group">		
				<select name="company" id="company" class="form-control">
					<option value="0">Any Company</option>
					@foreach($allCompanies as $company)
					<option value="{{$company->getRef()}}"  
						@if($filter['fcompany'] == $company->id) 
							selected
						@endif 
					>{{$company->getRef()}} - {{$company->companyname}}</option>
					@endforeach
				</select>
			</div>
			<div class="btn-group dashhead-toolbar-item">
					<button type="submit" tabindex="4" class="btn btn-outline-primary"> 
					<span class="icon icon-funnel"></span> Filter</button>
			</div>
			</form>		
		</div>
</div>

 <div class="col-md-12">
 
 
 {{ $notes->links() }}

	<div class="table-responsive">
	<table id="noteTable" class="table" data-sort="table">
		<thead>
			<tr>
				<th class="header">View</th>
				<th class="header">Company</th>
				<th class="header">Note</th>
				<th class="header">Date</th>
				<th class="header">User</th>
			</tr>
		</thead>
	<tbody>
	@foreach($notes as $note)
	<tr>
		<td><a href="{{ route('admin.notes.show',['id'=>$note->id])}}">View</a></td>
		<td>{{$note->company->companyname}}</td>
		<td>{{$note->message}}</td>
		<td>{{$note->updated_at}}</td>
		<td>{{$note->createdby->fullName()}}</td>
	</tr>
	@endforeach
	</tbody>
	</table>
	</div>

	{{ $notes->links() }}
</div>
@endsection
@section('addscripts')
<script>
	$(document).ready(function() 
		{ 
			$("#noteTable").tablesorter(); 
		} 
	); 

</script>
@endsection

resources/views/admin/notes/show.blade.php
@extends('admin.layouts.app')

@section('title','Note')

@section('content')
 <div class="col-md-12">
 <div class="btn-group">
      <a title="Note List" type="button" class="btn btn-outline-primary" href="{{route('admin.notes.index')}}">
        <span class="icon icon-list"></span>
      </a>
</div>

 		<dl class="row">
			<dt class="col-sm-4">Company Name</dt>
			<dd class="col-sm-8">{{$note->company->companyname}}</dd>
			<dt class="col-sm-4">Note</dt>
			<dd class="col-sm-8">{{$note->message}}</dd>
			<dt class="col-sm-4">Date</dt>
			<dd class="col-sm-8">{{$note->updated_at}}</dd>
			<dt class="col-sm-4">User</dt>
			<dd class="col-sm-8">{{$note->createdby->fullName()}}</dd>
		</dl>
</div>
@endsection